### ISSUE TITLE
wrong component name when checking rof/ocn same grid 

### ISSUE THREAD

**Issue by tomaslovato** [ESCOMP/CESM_CPL7andDataComps#14]
In the case runoff is provided over the same grid of the ocean model, 
the code fails returning an error in the comparison of runoff and ocean grids size.

This is due to a bug in the retrieval of the `rof` component grid in the following 
https://github.com/ESCOMP/CESM_CPL7andDataComps/blob/0abdb34d0ccb7e75399282b20bd7a1f231357f00/driver/main/seq_domain_mct.F90#L336
which is erroneously requesting the grid of the `glc` component.

Replacing `glc` with  `rof` will solve the issue.

**Comment by tomaslovato** [comment]
Is there any possibility that this issue will be somehow addressed? 

Maybe @jedwards4b that recently pushed to this repo could you give us a hint...

Thanks for any feedback

**Comment by jedwards4b** [comment]
@tomaslovato  Your suggested fix looks correct - can you suggest a compset and layout that will reproduce the problem so that I can test it?

**Comment by tomaslovato** [comment]
Thanks for the reply @jedwards4b.
At the moment we are developing an _in-house_ configuration of CESM with NEMO ocean model and out own global runoff dataset (on the same ocean grid), so I cannot point you to a reference compset to reproduce the issue ...

Besides, looking at the code it emerges that this is likely a typo occurred in the code development phase but not detected with standard configurations. .

**Comment by jedwards4b** [comment]
I agree - I can create a new tag based on your confirmation that this change works, we are not using the mct driver any longer.

**Comment by jedwards4b** [comment]
@tomaslovato please try [cpl77.0.4](https://github.com/ESCOMP/CESM_CPL7andDataComps/releases/tag/cpl77.0.4)

**Comment by tomaslovato** [comment]
Thanks @jedwards4b . I'll point the person working on this activity and let you know if any issue arise with the updated code.
